CREATE database bi;

use bi;


CREATE TABLE `party_detail_type_lu` (
  `PK_PARTY_DETAIL_TYPE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PARTY_DETAIL_TYPE_NAME` varchar(50) DEFAULT NULL,
  `FK_PARTY_TYPE_ID` int(5) DEFAULT NULL,
  PRIMARY KEY (`PK_PARTY_DETAIL_TYPE_ID`),
  KEY `PARTY_TYPE_LU_fk1` (`FK_PARTY_TYPE_ID`),
  CONSTRAINT `PARTY_TYPE_LU_fk1` FOREIGN KEY (`FK_PARTY_TYPE_ID`) REFERENCES `party_type_lu` (`PK_PARTY_TYPE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

CREATE TABLE `party_info` (
  `PK_PARTY_ID` int(10) NOT NULL AUTO_INCREMENT,
  `PARTY_NAME` varchar(50) DEFAULT NULL,
  `PARTY_ADDRESS_LINE_1` varchar(50) DEFAULT NULL,
  `PARTY_ADDRESS_LINE_2` varchar(50) DEFAULT NULL,
  `PARTY_EMAIL_ID` varchar(45) DEFAULT NULL,
  `PARTY_MOBILE_NO` double DEFAULT NULL,
  `PARTY_TEL_NO` int(15) DEFAULT NULL,
  `FK_PARTY_TYPE_ID` int(5) DEFAULT NULL,
  `FK_PARTY_DETAIL_TYPE_ID` int(5) DEFAULT NULL,
  PRIMARY KEY (`PK_PARTY_ID`),
  KEY `PARTY_INFO_fk2` (`FK_PARTY_DETAIL_TYPE_ID`),
  KEY `PARTY_INFO_fk3_idx` (`FK_PARTY_TYPE_ID`),
  CONSTRAINT `PARTY_INFO_fk2` FOREIGN KEY (`FK_PARTY_DETAIL_TYPE_ID`) REFERENCES `party_detail_type_lu` (`PK_PARTY_DETAIL_TYPE_ID`),
  CONSTRAINT `PARTY_INFO_fk3` FOREIGN KEY (`FK_PARTY_TYPE_ID`) REFERENCES `party_type_lu` (`PK_PARTY_TYPE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=latin1;

CREATE TABLE `party_type_lu` (
  `PK_PARTY_TYPE_ID` int(5) NOT NULL AUTO_INCREMENT,
  `PARTY_TYPE_NAME` varchar(50) DEFAULT NULL,
  `CREATE_DATE` date DEFAULT NULL,
  PRIMARY KEY (`PK_PARTY_TYPE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

CREATE TABLE `users` (
  `PK_USER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(10) DEFAULT NULL,
  `PASSWORD` varchar(60) DEFAULT NULL,
  `access` int(5) DEFAULT NULL,
  `FK_PARTY_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`PK_USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=latin1;